[project]
name = "static-code-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bandit>=1.8.6",
    "flake8>=7.3.0",
    "pylint>=4.0.2",
]
